# Операції над масивами
> хоча базово всі дані інтерпретуються як масиви, можливо працювавти з двовимірними масивами як алгебраїчними матрицями.

In [1]:
def homework(message):
    print("\n>>>>>", message, "\n")
def answer(message):
    print("Відповідь:", message, "\n")
import numpy as np

> згенеруємо декілька масивів різними способами та виконаємо базові математичні операції.

In [2]:
l = (3, 3)

O = np.ones(l)
R = np.random.random(l)
Z = np.zeros(l)
C = np.arange(l[0])

print(f"""
Віднімання:\n {C - (O + 10)}
Множення:\n {O * R}
Ділення:\n {R / C}
Степінь:\n {C ** Z}
Поріняння:\n {R > 0.5}
Ділення на 0:\n {O / Z}
""")
homework("""
- Створіть власну матрицю за допомогою методу eye та виконайте порівняння на наявність 1.
- Створіть матрицю ones та відніміть від неї матрицю eye (щоб у результаті вийшла матриця де цетнтральні діагональ все нулі).
""")
eye_matrix = np.eye(3)
print("Матриця eye:")
print(eye_matrix)

print("\nПорівняння на наявність 1 у матриці eye:")
print(eye_matrix == 1)

ones_matrix = np.ones((3, 3))
print("\nМатриця ones:")
print(ones_matrix)

result_matrix = ones_matrix - eye_matrix
print("\nРезультат віднімання ones - eye (де центральні діагоналі будуть нулями):")
print(result_matrix)


Віднімання:
 [[-11. -10.  -9.]
 [-11. -10.  -9.]
 [-11. -10.  -9.]]
Множення:
 [[0.87415714 0.91505847 0.61284301]
 [0.49253387 0.02273586 0.09710004]
 [0.58016266 0.25352186 0.02424187]]
Ділення:
 [[       inf 0.91505847 0.30642151]
 [       inf 0.02273586 0.04855002]
 [       inf 0.25352186 0.01212094]]
Степінь:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Поріняння:
 [[ True  True  True]
 [False False False]
 [ True False False]]
Ділення на 0:
 [[inf inf inf]
 [inf inf inf]
 [inf inf inf]]


>>>>> 
- Створіть власну матрицю за допомогою методу eye та виконайте порівняння на наявність 1.
- Створіть матрицю ones та відніміть від неї матрицю eye (щоб у результаті вийшла матриця де цетнтральні діагональ все нулі).
 

Матриця eye:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Порівняння на наявність 1 у матриці eye:
[[ True False False]
 [False  True False]
 [False False  True]]

Матриця ones:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

Результат віднімання ones - eye (де центральні діагоналі будуть нулями)

C:\Users\sanya\AppData\Local\Temp\ipykernel_3736\3970923811.py:11: RuntimeWarning: divide by zero encountered in divide
  Ділення:\n {R / C}
C:\Users\sanya\AppData\Local\Temp\ipykernel_3736\3970923811.py:14: RuntimeWarning: divide by zero encountered in divide
  Ділення на 0:\n {O / Z}


# Множення матриць
>  якщо маси яно не задати як матрицю, тоді операції будуть виконуавтись до кожного елемента.

In [5]:
A = np.array([ [1, 2, 3], [2, 2, 2], [3, 3, 3] ])
B = np.array([ [3, 2, 1], [1, 2, 3], [-1, -2, -3] ])

print(f"Маємо два масиви:\n {A} \n {B}")

R = A * B
print(f"Тут виконується поелементне множення:\n {R}")

# Множення матриць
R = np.dot(A, B)
print(f"Тут, масиви перемножуються як матриці:\n {R}")

MA = np.asmatrix(A)
MB = np.asmatrix(B)

R = MA * MB
print(f"Тут масиви перетворені на матриці і далі перемножуються:\n {R}")

Маємо два масиви:
 [[1 2 3]
 [2 2 2]
 [3 3 3]] 
 [[ 3  2  1]
 [ 1  2  3]
 [-1 -2 -3]]
Тут виконується поелементне множення:
 [[ 3  4  3]
 [ 2  4  6]
 [-3 -6 -9]]
Тут, масиви перемножуються як матриці:
 [[ 2  0 -2]
 [ 6  4  2]
 [ 9  6  3]]
Тут масиви перетворені на матриці і далі перемножуються:
 [[ 2  0 -2]
 [ 6  4  2]
 [ 9  6  3]]


# Вирівнювання розмірностей
> broadcasting - механізм який дозволяє вирівняти розмірність масивів для того щоб здійснити операцію над кожним його елементом. Масиви повинні бути співрозмірні, або один з вимірівв має бути 1 (рядок або стопець).

In [4]:
A = np.array([ [11, 12, 13], [21, 22, 23], [31, 32, 33] ])
B = np.array([1, 2, 3])
C = B[:, np.newaxis]

print(f"Вектор В є рядком {B.shape}: {B} тому додавання буде по рядках:\n {A + B}")

print(f"""Вектор C є стовпцем {C.shape}:
{C}
тому додавання буде по стовпцям:
{A + C}""")

print(f"У випадку додавання рядка до стовпця буде матриця в якої доповнюються рядки і стовпці:\n {B + C}")

Вектор В є рядком (3,): [1 2 3] тому додавання буде по рядках:
 [[12 14 16]
 [22 24 26]
 [32 34 36]]
Вектор C є стовпцем (3, 1):
[[1]
 [2]
 [3]]
тому додавання буде по стовпцям:
[[12 13 14]
 [23 24 25]
 [34 35 36]]
У випадку додавання рядка до стовпця буде матриця в якої доповнюються рядки і стовпці:
 [[2 3 4]
 [3 4 5]
 [4 5 6]]


# Конкатенація, повторення та зміна форми (shape)
> конкатенація (`concatenate`) - процес зчеплення двох і більше елементів (рядків, стовпців), у нашому випадку масивів які мають однакову форму shape;

> повторення (`tile`) - процес побудови масива шляхом повторення заданого елемента;

> зміна форми (`reshape`) або розмірності масива за умови що сумарна розмірність залишиться незмінною;

In [13]:
D = np.ones(3)
Z = np.zeros((3, 1))
B = np.array([[3, 2, 1], [1, 2, 3], [-1, -2, -3]])
C = np.arange(1, 13).reshape(3, 4)

print(f"""
При конкатенації рядків маємо: {np.concatenate((D, D))}")
При конкатенації стовпців маємо:\n{np.concatenate((Z, Z))}
Масив D {D} має розмірність {D.shape} тому може виконати операцію конкатенації з B {B.shape}:
{np.concatenate((B, D.reshape(1, 3)))}  # reshape D, щоб співпало по розміру

Для конкатенації з C:
{C}
де C має розмірність = {C.shape} потрібно змінити розмірність D = {D.shape}
Це можна ось так:
{D[:, np.newaxis].shape}
або
{D.reshape((3,1)).shape}
в результаті ми можемо виконати конкатенацію:
{np.concatenate((C, D.reshape(3,1)), axis=1)}  # Зміна осі для конкатенації по стовпцях

При повторенні D {D} 2 рази для рядків та 3 для стовпців будемо мати:
{np.tile(D, (2, 3))}

Як бачимо, конкатенація та повторення є схожими у деяких випадках:
- конкатенація: {np.concatenate((D, D))}
- повторення: {np.tile(D, 2)}

Також можна перетворити двовимірний масив C розмірністю {C.shape} на рядок: {C.flatten()} з розмірністю {C.flatten().shape}
""")

homework(f"""Створіть двохвимірний масив за допомогою arange та виконайте конкатенацію та повторення.
Створіть масив в якому кількість рядкі та стовпців різна. Спробуйте виконати конкатенацію такого масиву з попереднім. Якщо розмірність масивів не спаівпадє використайте reshape.
Створіть декіль двовимірних масивів з сумарною розмірністю 12 та знайдіть всі можливі комбінції reshape. Наприклад, перша комбінація це рядок - {np.ones((1,12))}
""")

print(f"Масив C: {C}\n")

D2 = np.arange(1, 13).reshape(4, 3)
print(f"Масив D2: {D2}\n")

if C.shape[1] == D2.shape[1]:
    print(f"Конкатенація C та D2: {np.concatenate((C, D2), axis=0)}")
else:
    D2_resized = D2.reshape(3, 4)
    print(f"Конкатенація C та D2 після reshape: {np.concatenate((C, D2_resized), axis=0)}")

print("Всі можливі комбінації reshape для масиву з розмірністю 12:")
for i in range(1, 13):
    for j in range(1, 13):
        if i * j == 12:
            print(np.ones((i, j)))



При конкатенації рядків маємо: [1. 1. 1. 1. 1. 1.]")
При конкатенації стовпців маємо:
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]
Масив D [1. 1. 1.] має розмірність (3,) тому може виконати операцію конкатенації з B (3, 3):
[[ 3.  2.  1.]
 [ 1.  2.  3.]
 [-1. -2. -3.]
 [ 1.  1.  1.]]  # reshape D, щоб співпало по розміру

Для конкатенації з C:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
де C має розмірність = (3, 4) потрібно змінити розмірність D = (3,)
Це можна ось так:
(3, 1)
або
(3, 1)
в результаті ми можемо виконати конкатенацію:
[[ 1.  2.  3.  4.  1.]
 [ 5.  6.  7.  8.  1.]
 [ 9. 10. 11. 12.  1.]]  # Зміна осі для конкатенації по стовпцях

При повторенні D [1. 1. 1.] 2 рази для рядків та 3 для стовпців будемо мати:
[[1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]]

Як бачимо, конкатенація та повторення є схожими у деяких випадках:
- конкатенація: [1. 1. 1. 1. 1. 1.]
- повторення: [1. 1. 1. 1. 1. 1.]

Також можна перетворити двовимірний масив C розмірністю (3, 4) на рядок: [ 

# Трансформації масивів
> масии можуть бути трансформовані багатьма способами зміщюючи позиції рядкі або стопців;

> транспонація - заміна рядкі на стопці;

> функції `size` та `shape` - дозволяють визначити кількість елементів 

In [14]:
O = np.arange(6).reshape(3,2)
O_r = O.reshape((2,3))
O_f = O.flatten()
O_t = O.transpose()
O_fl = np.flip(O)
O_fa = np.flip(O, axis=1)

print(f"""{O}
Змінити розмірність shape {O.shape} на {O_r.shape} при цьому розмір size {O.size} = {O_r.size} та ndim {np.ndim(O)} = {np.ndim(O_r)}:
{O_r}
Також можна перетворити {np.ndim(O)}-х вимірний масив розмірністю {O.shape} на рядок:
{O_f} 
з розмірністю {O_f.shape} при цьому size = {O_f.size} та ndim стане {np.ndim(O_f)}-х вимірним 
Або транспонувати масив щоб він став {O_t.shape} але зверніть увагу на елементи:
{O_t}
Можна обернути масив (обертаємо по стовпцях і рядках одночасно): 
{O_fl}
Або обернути лише елементи в кожному рядку (або стовпці):
{O_fa}
""")

homework("""
- Створіть вектор з 12 елементів, визначте його shape, size та ndim;
- Змініть розмірніть перетворивши вектор у матрицю;
- Здійсніть транспонування отриманої матриці та оберніть її;
- Перетворіть отриманий багатовимірний масив назад у вектор (стрічку);
""")
vector = np.arange(12)

vector_shape = vector.shape
vector_size = vector.size
vector_ndim = np.ndim(vector)

matrix = vector.reshape(3, 4)

transposed_matrix = matrix.transpose()

flipped_matrix = np.flip(matrix)

flattened_matrix = matrix.flatten()

print(f"Вектор:\n{vector}\n")
print(f"Shape: {vector_shape}, Size: {vector_size}, ndim: {vector_ndim}\n")
print(f"Матриця після зміни розміру:\n{matrix}\n")
print(f"Транспонована матриця:\n{transposed_matrix}\n")
print(f"Обернена матриця:\n{flipped_matrix}\n")
print(f"Перетворений вектор (flattened):\n{flattened_matrix}\n")

[[0 1]
 [2 3]
 [4 5]]
Змінити розмірність shape (3, 2) на (2, 3) при цьому розмір size 6 = 6 та ndim 2 = 2:
[[0 1 2]
 [3 4 5]]
Також можна перетворити 2-х вимірний масив розмірністю (3, 2) на рядок:
[0 1 2 3 4 5] 
з розмірністю (6,) при цьому size = 6 та ndim стане 1-х вимірним 
Або транспонувати масив щоб він став (2, 3) але зверніть увагу на елементи:
[[0 2 4]
 [1 3 5]]
Можна обернути масив (обертаємо по стовпцях і рядках одночасно): 
[[5 4]
 [3 2]
 [1 0]]
Або обернути лише елементи в кожному рядку (або стовпці):
[[1 0]
 [3 2]
 [5 4]]


>>>>> 
- Створіть вектор з 12 елементів, визначте його shape, size та ndim;
- Змініть розмірніть перетворивши вектор у матрицю;
- Здійсніть транспонування отриманої матриці та оберніть її;
- Перетворіть отриманий багатовимірний масив назад у вектор (стрічку);
 

Вектор:
[ 0  1  2  3  4  5  6  7  8  9 10 11]

Shape: (12,), Size: 12, ndim: 1

Матриця після зміни розміру:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Транспонована матриця:
[[ 0  4  8]
 